### ISSUE TITLE
Update apt repository

### ISSUE THREAD

**Issue by tnation14** [azavea/ansible-pcp#1]
The PCP bintray repository has been renamed to https://dl.bintray.com/pcp/<distribution>, and the apt-key URL has changed to https://bintray.com/user/downloadSubjectPublicKey?username=pcp. These need to be updated in the role so that `apt` does not attempt to install an unauthenticated package.

**Comment by jwalgran** [comment]
OpenTreeMap ran into development-only provisioning problems as a result of the pcp renaming. We are working around it on our dev VMs by removing the pcp role dependency from our playbook.
